name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 23 * * *'
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: ['Chrome_Desktop', 'Firefox_Desktop', 'Safari_Desktop', 'Logged_In']
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Cache Node.js modules
        uses: actions/cache@v4
        id: node-modules-cache
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            node-modules-${{ runner.os }}-

      - name: Install dependencies
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Setup
        run: npx playwright test --project=newUserSignUpAndLogin

      - name: Run Playwright tests
        env:
          SIGNIN_USERNAME: ${{ secrets.SIGNIN_USERNAME }}
          SIGNIN_PASSWORD: ${{ secrets.SIGNIN_PASSWORD }}
          BROWSER: ${{ matrix.browser }}
        run: npx playwright test --project=${{ matrix.browser }}

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-${{ matrix.browser }}
          path: playwright-report/${{ matrix.browser }}
          retention-days: 30